#!/usr/bin/env bash

echo "Fetching dependencies to $GOPATH..."
printf "   (00/06)\r"
  go get -u github.com/stretchr/testify
printf "   (01/06)\r"
  go get -u github.com/ivotron/peg
printf "   (02/06)\r"
  go get -u github.com/mattn/go-sqlite3
printf "   (03/06)\r"
  go get -u github.com/spf13/cobra
printf "   (04/06)\r"
  go get -u github.com/bitly/go-simplejson
printf "   (05/06)\r"
  go get -u github.com/ivotron/textql
printf "## (06/06)\r"
printf "\n"
